#!/bin/bash
# PGPASSWORD=postgres

import_sql(){
    gunzip -c ./.data/aligulac.sql.gz | \
    PGPASSWORD=postgres psql -h postgres -p 5432 -d postgres -U postgres 
    #  psql -h postgresdb -p 5432 -d aligulac -c  "CREATE ROLE aligulac"
}

import(){
     PGPASSWORD=postgres psql -h postgres -p 5432 -d postgresdb -U postgres \
     -c "SELECT * FROM titles"
}

"$@"
