version: "3.2"


services:

  base:
    image: moviequery.base
    build:
      context: ./base
      dockerfile: ./Dockerfile
    command: tail -f /dev/null
    stdin_open: true
    tty: true

  lab:
    image: moviequery.lab
    volumes:
      - ../lab:/opt/app
      - ../.data:/opt/.data
    build:
      context: ../lab
      dockerfile: ./Dockerfile
    ports:
      - 7788:7878
      - 7080:8080
      # - 7878:7878
      # - 11488:7888
      # - 12083:8080
    command: bash c dev
    # command: tail -f /dev/null
    stdin_open: true
    tty: true
    links:
      - base
      - server
      - zero
      - ratel 
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8096M
        # reservations:
        #   cpus: '0.25'
        #   memory: 20M

  load-pgsql:
    image: moviequery.load-pgsql
    volumes:
      - ../load-pgsql:/opt/app
      - ../:/opt/data
    build:
      context: ../load-pgsql
      dockerfile: ./Dockerfile
    command: tail -f /dev/null
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8096M