version: "3.2"


services:

   lab:
    image: probe.lab
    volumes:
      - ../lab:/opt/app
    build:
      context: ../lab
      dockerfile: ./Dockerfile
    ports:
      - 7010:7878
      # - 7878:7878
      # - 11488:7888
      # - 12083:8080
    command: bash c dev
    # command: tail -f /dev/null
    stdin_open: true
    tty: true
    links:
      - server
      - zero
      - ratel 
