version: "3.2"

services:
  postgres:
    image: postgres:11.1
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgresdb
      POSTGRES_PASSWORD: postgres
    volumes:
      - type: volume
        source: moviequery.imdb.postgres
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
      - ../:/opt
    stdin_open: true
    tty: true

  adminer:
    image: adminer
    # restart: always
    ports:
      - 7088:8080


volumes:
  moviequery.imdb.postgres: